version: '3.7'
services:
  airsonic:
    image: linuxserver/airsonic:latest
    container_name: airsonic
    hostname: airsonic
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
      - ../Data/music:/music
      - ../Data/playlists:/playlists
      - ../Data/podcasts:/podcasts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.airsonic.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.airsonic.entrypoints=web-secure"
      - "traefik.http.routers.airsonic.middlewares=default-headers@file"
      - "traefik.http.routers.airsonic.service=airsonic"
      - "traefik.http.routers.airsonic.tls=true"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040" # Proxied Port
